blueprint:
  name: "[Z2M] - Philips dimmer v1"
  description: Control lights with a button including brightness up/down, on/off, and adjustable delay.
  domain: automation
  input:
    button_device:
      name: Button Device
      description: Select the button to control the lights
      selector:
        device:
          - integration: mqtt
    target_lights:
      name: Lights to Control
      description: Lights to control with this button
      selector:
        target:
          entity:
            domain: light
    step_delay:
      name: Delay Between Brightness Steps
      description: Delay in seconds between brightness steps when holding the button
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
    transition_time:
      name: Light Transition Time
      description: Transition time for on/off or brightness steps
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 0.1

trigger:
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: "off_press"
    id: "off"
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: "on_press"
    id: "on"
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: "up_press"
    id: "brightness-up"
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: "down_press"
    id: "brightness-down"
  - platform: device
    device_id: !input button_device
    domain: mqtt
    type: action
    subtype: "brightness_stop"
    id: "brightness-stop"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - service: light.turn_off
            target: !input target_lights
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: light.turn_on
            target: !input target_lights
            data:
              transition: !input transition_time
      - conditions:
          - condition: trigger
            id:
              - "brightness-up"
              - "brightness-stop"
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - "brightness-stop"
              sequence:
                - service: light.turn_on
                  target: !input target_lights
                  data:
                    brightness_step_pct: 10
                    transition: !input transition_time
                - delay:
                    seconds: !input step_delay
      - conditions:
          - condition: trigger
            id:
              - "brightness-down"
              - "brightness-stop"
        sequence:
          - repeat:
              until:
                - condition: trigger
                  id:
                    - "brightness-stop"
              sequence:
                - service: light.turn_on
                  target: !input target_lights
                  data:
                    brightness_step_pct: -10
                    transition: !input transition_time
                - delay:
                    seconds: !input step_delay
mode: restart
